[package]
name = "system_f_omega"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paris = "1.5"
system-f-omega-macros = { path="../system-f-omega-macros" }